#
# See default configuration here: https://github.com/codecov/support/blob/master/codecov.yml
#
# For more options see: https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a
#
# Codecov documentation is available here: https://codecov.io/docs

codecov:
  branch: master
  bot: null

coverage:
  status:
     project:
       default:
         target: auto
         threshold: null
         branches: null

comment:
  layout: "header, diff, changes, uncovered"
