name: Build under Ubuntu

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: zulu
          cache: gradle

      - name: Decrypt Firebase service account
        run: chmod +x ./scripts/decrypt.sh && \
             ./scripts/decrypt.sh "$FIREBASE_CREDS_KEY" \
             ./.github/keys/service-account.json.gpg \
             ./deployment/appengine-web/src/main/resources/service-account.json
        env:
          FIREBASE_CREDS_KEY: ${{ secrets.FIREBASE_CREDS_KEY }}

      - name: Build project and run tests
        shell: bash
        run: ./gradlew build --stacktrace
