name: Deploy to AppEngine

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: zulu
          cache: gradle

      - name: Decrypt Firebase service account
        run: ./scripts/decrypt.sh "$FIREBASE_CREDS_KEY" ./.github/keys/service-account.json.gpg ./deployment/appengine-web/src/main/resources/service-account.json
        env:
          FIREBASE_CREDS_KEY: ${{ secrets.FIREBASE_CREDS_KEY }}

      - name: Prepare GCloud credentials
        run: gcloud auth activate-service-account --key-file ./deployment/appengine-web/src/main/resources/service-account.json

      - name: Prepare GCloud project ID
        run: gcloud config set project spine-todo-list-example

      - name: Build aftifacts
        run: ./gradlew :appengine-web:war -PbuildProfile=dev --stacktrace

      - name: Deploy aftifacts
        run: ./gradlew :appengine-web:appengineDeploy -PbuildProfile=dev --stacktrace
